### ISSUE TITLE
giving filepath as argument, openat returns -2.

### ISSUE THREAD

**Issue by hardik05** [zeropointdynamics/zelos#130]
**Describe the bug**
if a program expects filename as argument, file open fails. error code -2.

**To Reproduce**
1. compile this program:
https://github.com/hardik05/Damn_Vulnerable_C_Program/blob/master/imgRead.c
gcc imgRead.c -o imgRead 

2. this program expects a file name as argument. 
create a sample file:
echo "Hello" > 1.img

3. run compiled binary with zelos as below:
zelos imgRead 1.img

file open will fail, following message will be displayed:
```
10:12:39:hooks_____:INFO__:Reached entrypoint 0x20c0
[main] [SYSCALL] brk ( addr=0x0 ) -> 90000040
[main] [SYSCALL] brk ( addr=0x90021040 ) -> 90021040
[main] [SYSCALL] brk ( addr=0x90022000 ) -> 90022000
[main] [SYSCALL] openat ( dirfd=0xffffff9c, pathname=0x7f000008eebb ("imgread"), flags=0x0 ) -> -2
[main] [SYSCALL] fstat ( fd=0x1 (stdout), statbuf=0x7f000008e460 ) -> 0
IOCTL: 186814848
[main] [SYSCALL] ioctl ( fd=0x1 (stdout), request=0x5401, data=0x7f000008e3c0 ) -> -1
[StdOut]: 'b"\nCan't open file or file doesn't exist."'
[main] [SYSCALL] write ( fd=0x1 (stdout), buf=0x900004d0 ("\nCan't open file or file doesn't exist."), count=0x27 ) -> 27

```

**Expected behavior**
file open should be successful. is it a file path issue? may be i am giving it wrong?

**Screenshots**
NA

**Additional context**
NA

**Comment by hardik05** [comment]
@rcourt any idea where to look for this ? i am trying to debug it but couldn't figure it out.

**Comment by hardik05** [comment]
i had a look at the code and it seems that the issue is in  zelos/src/zelos/ext/platforms/linux/syscalls/syscalls.py in xopen function, it checks for flags and then returns.:

  ```
 pathname_s = p.memory.read_string(args.pathname)
    path = k.z.files.find_library(pathname_s)
    k.z.triggers.tr_file_open(pathname_s)
    if path is not None:
        handle_num = k.z.handles.new_file(pathname_s)
        retval = handle_num
    elif args.flags & 0x200 != 0 or args.flags & 0x40 != 0:
        handle_num = k.z.handles.new_file(pathname_s)
        retval = handle_num
    else:
        return SysError.ENOENT
    return retval
```
i have made  a temp fix by adding this line:
```
elif args.flags == 0:
        handle_num = k.z.handles.new_file(pathname_s)
        retval = handle_num

```

but then it fails at ioctl call which return -1, seems that this is not implemented or i am not able to figure it out myself.

**Comment by kvalakuzhyzp** [comment]
In order to read files outside of the executable, you have to `mount` the file (or folder) so that Zelos knows that it is allowed to see it. This is to reduce the chance of unintended access to the files of the machine you are running Zelos on.

In order to avoid this error, try changing your 3rd command to 

`zelos imgRead 1.img --mount=x86,1.img,1.img`

This command lets Zelos know that there is a file called '1.img' locally that should be seen in the emulated system as the file named '1.img'.
The initial 'x86' is a detail on the architecture, which I hope to remove the need for in the near future.

**Comment by hardik05** [comment]
Thanks for looking at it. tried with  --mount option but getting this message:
 "There are no lines in source that correspond to the taint path. There may have been a bug."
any idea? .zcov files are not getting generated..

**Comment by hardik05** [comment]
here is a simple file. this file crashes the sample program and so i want to generated taint graph.
[2.zip](https://github.com/zeropointdynamics/zelos/files/5577240/2.zip)

**Comment by kvalakuzhyzp** [comment]
Double checking, you have the zelos-crashd plugin installed? Are you passing additional flags for the taint capabilities mentioned in zelos-crashd?

**Comment by hardik05** [comment]
Yes i have crashes installed and giving args for it.

Zelos -taint -taint_output=terminal ./imgread 1.img -mount=x86,1.img,1.img

**Comment by kvalakuzhyzp** [comment]
The reason you are getting that error is because the file you are analyzing doesn't have any debug symbols. This plugin reads debug symbols in order to figure out the lines of source code that correspond to the crashing lines. If you compile your example file with the `-g` compile flag `gcc imgRead.c -g -o imgRead` you will include debug information. 

Rerun the command after you include debug information in your `imgread` binary, and you should get the information you need.

Please reopen this issue if this does not fix your problem.

**Comment by hardik05** [comment]
Thanks for your help. its working now as expected.
